In [ ]:
#numpy

In [ ]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
x=np.array([1,0,0,0])
print("original array")
print(x)
print(np.any(x))
x=np.array([0,0,0,0])
print(np.any(x))

original array
[1 0 0 0]
True
False


In [ ]:
import numpy as np
array=np.array([1,-2,np.inf,-np.inf,0,3.25])
pos=np.isposinf(array)
neg=np.isneginf(array)
print(pos)
print(neg)

[False False  True False False False]
[False False False  True False False]


In [ ]:
import numpy as np
array=np.array([1,0,np.nan,np.inf])
print(array)
print("test elements")
print(np.isnan(array))


[ 1.  0. nan inf]
test elements
[False False  True False]


In [ ]:
import numpy as np
array=np.arange(30,71)
print(array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
import numpy as np
array=np.identity(3)
print(array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
arr1=[1,2,3,4]
arr2=[5,6,7,8]
add=np.add(arr1,arr2)
print(add)


[ 6  8 10 12]


In [ ]:
arr=np.array([[1,2,3,4],[0,1,3,4],[90,91,93,94],[5,0,3,2]])
print(arr)
print("reverse")
print(arr[::-1])
print("transpose")
transpose_arr=arr.transpose()
print(transpose_arr)

[[ 1  2  3  4]
 [ 0  1  3  4]
 [90 91 93 94]
 [ 5  0  3  2]]
reverse
[[ 5  0  3  2]
 [90 91 93 94]
 [ 0  1  3  4]
 [ 1  2  3  4]]
transpose
[[ 1  0 90  5]
 [ 2  1 91  0]
 [ 3  3 93  3]
 [ 4  4 94  2]]


In [ ]:
arr=np.array([[1,2,3,4],[0,1,3,4],[90,91,93,94],[5,0,3,2]])
